"""Sim gate for gemv_banked_resident_vec — the P-WIDE-boundary resident GEMV
core, generalized this session to support INT8 weights (WBW=8) alongside
checkpoint C's own INT4 scheme (WBW=4, the default, unchanged for every
existing build). No standalone gate existed for this specific module before
(it was only ever exercised indirectly through the full sequencer integration
tests, run_vec_seq.py/run_vec_kv.py) — this fills that gap AND is the direct
regression+new-capability gate for the WBW generalization itself.

    python -m fabric.stage3.run_resident_banked_vec                    # WBW=4 regression (must still pass)
    python -m fabric.stage3.run_resident_banked_vec --wbw 8             # new INT8 capability
    python -m fabric.stage3.run_resident_banked_vec --wbw 8 --k2 1      # INT8 + the K2 double-pump path
    python -m fabric.stage3.run_resident_banked_vec --lanes 64 --p 8 --shapes 384x128,384x128,512x384

Proves the resident-banked-vec core is BIT-EXACT vs the numpy golden with
>=2 layers preloaded at DIFFERENT w_base offsets, at a given LANES/WBW/P/K2 —
mirrors fabric/stage3/run_resident_banked.py's own multi-layer-offset
discipline, generalized to this module's P-wide activation/readback boundary
and its WBW lane width:
    BANKED_RESIDENT_VEC_VERDICT bitexact=True mismatches=0 ...
"""

from __future__ import annotations

import argparse
import os

from fabric.stage3._simdir import kevbuild
import subprocess
import sys

from . import pack_banked_resident_vec

HERE = os.path.dirname(os.path.abspath(__file__))
RTL = os.path.join(HERE, "rtl", "gemv_banked_resident_vec.sv")
RTL_WB = os.path.join(HERE, "rtl", "weight_bank_tdp.sv")


def gen_tb(sim_dir: str, manifest: dict, lanes: int, wbw: int, p: int,
           mmax: int, kmax: int, wwords: int, rlat: int, k2: int) -> str:
    """Emit a concrete (non-parameterised) testbench tuned to this case. Loads
    the whole resident w.mem once (32-bit chunks, same convention as
    run_resident_banked.py's), then per layer sets w_base/M/K, streams x{i}.mem
    P-wide, runs, and reads y{i}.out back P-wide (2-cycle latency, per the
    module's own header -- vs. the older resident core's 3-cycle/1-wide)."""
    n_words = manifest["n_words_total"]
    layers = manifest["layers"]
    wbits = lanes * wbw
    subw = (wbits + 31) // 32  # 32-bit load chunks per wide word

    run_blocks = []
    for i, lm in enumerate(layers):
        M, K, wb = lm["M"], lm["K"], lm["w_base"]
        n_xrows = K // p
        n_yrows = (M + p - 1) // p
        run_blocks.append(f"""
        // ---- layer {i}: w_base={wb} M={M} K={K} ----
        $readmemh("x{i}.mem", xload);
        ld_rst = 1; @(posedge clk); #1; ld_rst = 0;     // rewind x ptr (URAM kept)
        for (i2 = 0; i2 < {n_xrows}; i2 = i2 + 1) begin
            x_we = 1; x_data = xload[i2]; @(posedge clk); #1;
        end
        x_we = 0;
        m_count = {M}; k_count = {K}; w_base = {wb};
        start = 1; @(posedge clk); #1; start = 0;
        wait (done == 1'b1); @(posedge clk); #1;
        f = $fopen("y{i}.out", "w");
        for (i2 = 0; i2 < {n_yrows}; i2 = i2 + 1) begin
            rd_addr = i2;
            @(posedge clk); @(posedge clk); #1;   // 2-cycle readback latency
            for (i3 = 0; i3 < {p}; i3 = i3 + 1)
                $fwrite(f, "%08x\\n", y_out[i3*32 +: 32]);
        end
        $fclose(f);
        $display("LAYER_DONE {i} wbase={wb} M={M} K={K}");
""")

    tb = f"""// AUTO-GENERATED by fabric/stage3/run_resident_banked_vec.py — do not edit.
// gemv_banked_resident_vec gate: load whole model's transposed words once,
// run each layer at its w_base, dump y{{i}}.out for a Python bit-exact compare.
`timescale 1ns / 1ps
module tb;
    localparam integer LANES  = {lanes};
    localparam integer WBW    = {wbw};
    localparam integer P      = {p};
    localparam integer MMAX   = {mmax};
    localparam integer KMAX   = {kmax};
    localparam integer WWORDS = {wwords};
    localparam integer WBITS  = {wbits};
    localparam integer SUBW   = {subw};
    localparam integer NWORDS = {n_words};
    localparam integer K2     = {k2};

    reg clk = 1'b0;
    always #5 clk = ~clk;

    reg                       rst, ld_rst, w_we, x_we, start;
    reg [31:0]                w_data;
    reg [P*8-1:0]             x_data;
    reg [$clog2(MMAX+1)-1:0]  m_count;
    reg [$clog2(KMAX+1)-1:0]  k_count;
    reg [$clog2(WWORDS)-1:0]  w_base;
    reg [$clog2(MMAX/P)-1:0]  rd_addr;
    wire [P*32-1:0]           y_out;
    wire                      done;
    wire [$clog2((MMAX+LANES-1)/LANES+1)-1:0] gdone;
    wire [2*LANES*WBW-1:0]    emb_pair, wbdiag_pair;

    reg [WBITS-1:0]           wload [0:NWORDS-1];   // whole resident stream, wide words
    reg [P*8-1:0]             xload [0:KMAX/P-1];
    integer i, i2, i3, f, s;
    reg [WBITS-1:0]           word_tmp;

    gemv_banked_resident_vec #(.LANES(LANES), .WBW(WBW), .P(P), .MMAX(MMAX), .KMAX(KMAX),
                               .WWORDS(WWORDS), .RLAT({rlat}), .K2(K2),
                               .MEM_PRIMITIVE("block")) dut (
        .clk(clk), .rst(rst),
        .m_count(m_count), .k_count(k_count), .w_base(w_base),
        .ld_rst(ld_rst), .w_we(w_we), .w_data(w_data), .x_we(x_we), .x_data(x_data),
        .start(start), .done(done), .gdone(gdone),
        .rd_addr(rd_addr), .y_out(y_out),
        .emb_sel(1'b0), .emb_addr({{$clog2(WWORDS){{1'b0}}}}), .emb_pair(emb_pair),
        .wbdiag_addr({{$clog2(WWORDS){{1'b0}}}}), .wbdiag_pair(wbdiag_pair)
    );

    initial begin
        $readmemh("w.mem", wload);
        rst = 1; ld_rst = 1; w_we = 0; x_we = 0; start = 0;
        w_data = 0; x_data = 0; rd_addr = 0; m_count = 0; k_count = 0; w_base = 0;
        @(posedge clk); #1;
        rst = 0; ld_rst = 1; @(posedge clk); #1; ld_rst = 0;

        // ---- one-time resident load: each wide word as SUBW 32-bit chunks (low first)
        for (i = 0; i < NWORDS; i = i + 1) begin
            word_tmp = wload[i];
            for (s = 0; s < SUBW; s = s + 1) begin
                w_we = 1; w_data = word_tmp[s*32 +: 32]; @(posedge clk); #1;
            end
        end
        w_we = 0;
{''.join(run_blocks)}
        $display("TB_DONE nwords=%0d layers={len(layers)}", NWORDS);
        $finish;
    end

    initial begin
        #200000000;
        $display("TB_TIMEOUT");
        $finish;
    end
endmodule
"""
    tb_path = os.path.join(sim_dir, "tb_resident_banked_vec.sv")
    with open(tb_path, "w") as fh:
        fh.write(tb)
    return tb_path


def run(shapes, lanes, wbw, p, mmax, kmax, wwords, rlat, k2, seed, sim_dir) -> bool:
    os.makedirs(sim_dir, exist_ok=True)
    man = pack_banked_resident_vec.write_case(sim_dir, shapes, lanes, wbw, p, seed)
    if man["n_words_total"] > wwords:
        print(f"CONFIG_FAIL: need {man['n_words_total']} words > WWORDS={wwords}")
        return False
    tb = gen_tb(sim_dir, man, lanes, wbw, p, mmax, kmax, wwords, rlat, k2)

    vvp = os.path.join(sim_dir, "sim.vvp")
    cp = subprocess.run(["iverilog", "-g2012", "-o", vvp, tb, RTL, RTL_WB],
                         capture_output=True, text=True)
    if cp.returncode != 0:
        print("IVERILOG_COMPILE_FAIL")
        print(cp.stdout); print(cp.stderr)
        return False

    rp = subprocess.run(["vvp", "sim.vvp"], cwd=sim_dir, capture_output=True, text=True)
    sys.stdout.write(rp.stdout)
    if rp.returncode != 0 or "TB_DONE" not in rp.stdout:
        print("VVP_RUN_FAIL"); print(rp.stderr)
        return False

    return pack_banked_resident_vec.check(sim_dir)


def main(argv=None):
    p = argparse.ArgumentParser(prog="fabric.stage3.run_resident_banked_vec")
    p.add_argument("--shapes", default="256x128,128x128")
    p.add_argument("--lanes", type=int, default=64)
    p.add_argument("--wbw", type=int, default=4)
    p.add_argument("--p", type=int, default=8)
    p.add_argument("--mmax", type=int, default=1024)
    p.add_argument("--kmax", type=int, default=1024)
    p.add_argument("--wwords", type=int, default=16384)
    p.add_argument("--rlat", type=int, default=2)
    p.add_argument("--k2", type=int, default=0)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--dir", default=kevbuild("stage3_residentbankedvec"))
    a = p.parse_args(argv)
    shapes = [tuple(int(v) for v in s.split("x")) for s in a.shapes.split(",")]
    ok = run(shapes, a.lanes, a.wbw, a.p, a.mmax, a.kmax, a.wwords, a.rlat, a.k2, a.seed, a.dir)
    raise SystemExit(0 if ok else 1)


if __name__ == "__main__":
    main()
