"""Sim gate for the RESIDENT banked GEMV: gen multi-layer vectors -> generate a
testbench that loads the whole resident weight stream ONCE, then runs each layer
at its own w_base -> iverilog -> vvp -> bit-exact check across all layers/offsets.

    python -m fabric.stage3.run_resident_banked                 # default 2 layers, real-ish shapes
    python -m fabric.stage3.run_resident_banked --lanes 256 --shapes 768x256,256x256,1024x256

Proves the resident-banked core is BIT-EXACT vs the numpy golden with >=2 layers
preloaded at DIFFERENT w_base offsets — the gate the workstream requires:
    BANKED_RESIDENT_VERDICT bitexact=True mismatches=0 ...

Mirrors fabric/stage3/run_banked.py: the TB dumps y{i}.out per layer and the
Python file-based compare (pack_banked_resident.check) prints one sentinel.
"""

from __future__ import annotations

import argparse
import json
import os

from fabric.stage3._simdir import kevbuild
import subprocess
import sys

from . import pack_banked_resident

HERE = os.path.dirname(os.path.abspath(__file__))
RTL = os.path.join(HERE, "rtl", "gemv_banked_resident.sv")


# The 32-bit chunk count per wide word the core's load path expects.
def subw(lanes: int) -> int:
    return (lanes * 4) // 32


def gen_tb(sim_dir: str, manifest: dict, lanes: int, mmax: int, kmax: int,
           wwords: int, rlat: int) -> str:
    """Emit a concrete (non-parameterised) testbench tuned to this case. It loads
    the whole resident w.mem once (32-bit chunks), then per layer sets w_base/M/K,
    streams x{i}.mem, runs, and writes y{i}.out."""
    SUBW = subw(lanes)
    n_words = manifest["n_words_total"]
    layers = manifest["layers"]
    WBITS = lanes * 4

    # per-layer run blocks
    run_blocks = []
    for i, lm in enumerate(layers):
        M, K, wb = lm["M"], lm["K"], lm["w_base"]
        run_blocks.append(f"""
        // ---- layer {i}: w_base={wb} M={M} K={K} ----
        $readmemh("x{i}.mem", xload);
        ld_rst = 1; @(posedge clk); #1; ld_rst = 0;     // rewind x ptr (URAM kept)
        for (i2 = 0; i2 < {K}; i2 = i2 + 1) begin
            x_we = 1; x_data = xload[i2]; @(posedge clk); #1;
        end
        x_we = 0;
        m_count = {M}; k_count = {K}; w_base = {wb};
        start = 1; @(posedge clk); #1; start = 0;
        wait (done == 1'b1); @(posedge clk); #1;
        f = $fopen("y{i}.out", "w");
        for (i2 = 0; i2 < {M}; i2 = i2 + 1) begin
            rd_addr = i2;
            @(posedge clk); @(posedge clk); @(posedge clk); #1;
            $fwrite(f, "%08x\\n", y_out);
        end
        $fclose(f);
        $display("LAYER_DONE {i} wbase={wb} M={M} K={K}");
""")

    tb = f"""// AUTO-GENERATED by fabric/stage3/run_resident_banked.py — do not edit.
// Resident banked GEMV gate: load whole model's transposed words once, run each
// layer at its w_base, dump y{{i}}.out for a Python bit-exact compare.
`timescale 1ns / 1ps
module tb;
    localparam integer LANES  = {lanes};
    localparam integer MMAX   = {mmax};
    localparam integer KMAX   = {kmax};
    localparam integer WWORDS = {wwords};
    localparam integer WBITS  = {WBITS};
    localparam integer SUBW   = {SUBW};
    localparam integer NWORDS = {n_words};

    reg clk = 1'b0;
    always #5 clk = ~clk;

    reg                    rst, ld_rst, w_we, x_we, start;
    reg [31:0]             w_data;
    reg signed [7:0]       x_data;
    reg [15:0]             m_count, k_count;
    reg [$clog2(WWORDS)-1:0] w_base;
    reg [$clog2(MMAX)-1:0] rd_addr;
    wire signed [31:0]     y_out;
    wire                   done;

    reg [WBITS-1:0]        wload [0:NWORDS-1];   // whole resident stream, wide words
    reg [7:0]              xload [0:KMAX-1];
    integer i, i2, f, s;
    reg [WBITS-1:0]        word_tmp;

    gemv_banked_resident #(.LANES(LANES), .MMAX(MMAX), .KMAX(KMAX),
                           .WWORDS(WWORDS), .RLAT({rlat})) dut (
        .clk(clk), .rst(rst),
        .m_count(m_count[$clog2(MMAX+1)-1:0]), .k_count(k_count[$clog2(KMAX+1)-1:0]),
        .w_base(w_base),
        .ld_rst(ld_rst), .w_we(w_we), .w_data(w_data), .x_we(x_we), .x_data(x_data),
        .start(start), .done(done), .rd_addr(rd_addr), .y_out(y_out)
    );

    initial begin
        $readmemh("w.mem", wload);
        rst = 1; ld_rst = 1; w_we = 0; x_we = 0; start = 0;
        w_data = 0; x_data = 0; rd_addr = 0; m_count = 0; k_count = 0; w_base = 0;
        @(posedge clk); #1;
        rst = 0; ld_rst = 1; @(posedge clk); #1; ld_rst = 0;

        // ---- one-time resident load: each wide word as SUBW 32-bit chunks (low first)
        for (i = 0; i < NWORDS; i = i + 1) begin
            word_tmp = wload[i];
            for (s = 0; s < SUBW; s = s + 1) begin
                w_we = 1; w_data = word_tmp[s*32 +: 32]; @(posedge clk); #1;
            end
        end
        w_we = 0;
{''.join(run_blocks)}
        $display("TB_DONE nwords=%0d layers={len(layers)}", NWORDS);
        $finish;
    end

    initial begin
        #200000000;
        $display("TB_TIMEOUT");
        $finish;
    end
endmodule
"""
    tb_path = os.path.join(sim_dir, "tb_resident_banked.sv")
    with open(tb_path, "w") as fh:
        fh.write(tb)
    return tb_path


def run(shapes, lanes, mmax, kmax, wwords, rlat, seed, sim_dir) -> bool:
    os.makedirs(sim_dir, exist_ok=True)
    man = pack_banked_resident.write_case(sim_dir, shapes, lanes, seed)
    if man["n_words_total"] > wwords:
        print(f"CONFIG_FAIL: need {man['n_words_total']} words > WWORDS={wwords}")
        return False
    tb = gen_tb(sim_dir, man, lanes, mmax, kmax, wwords, rlat)

    vvp = os.path.join(sim_dir, "sim.vvp")
    cp = subprocess.run(["iverilog", "-g2012", "-o", vvp, tb, RTL],
                        capture_output=True, text=True)
    if cp.returncode != 0:
        print("IVERILOG_COMPILE_FAIL")
        print(cp.stdout); print(cp.stderr)
        return False

    rp = subprocess.run(["vvp", "sim.vvp"], cwd=sim_dir, capture_output=True, text=True)
    sys.stdout.write(rp.stdout)
    if rp.returncode != 0 or "TB_DONE" not in rp.stdout:
        print("VVP_RUN_FAIL"); print(rp.stderr)
        return False

    return pack_banked_resident.check(sim_dir)


def main(argv=None):
    p = argparse.ArgumentParser(prog="fabric.stage3.run_resident_banked")
    p.add_argument("--shapes", default="768x256,256x256")
    p.add_argument("--lanes", type=int, default=256)
    p.add_argument("--mmax", type=int, default=1024)
    p.add_argument("--kmax", type=int, default=1024)
    p.add_argument("--wwords", type=int, default=16384)
    p.add_argument("--rlat", type=int, default=2)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--dir", default=kevbuild("stage3_residentbanked"))
    a = p.parse_args(argv)
    shapes = [tuple(int(v) for v in s.split("x")) for s in a.shapes.split(",")]
    ok = run(shapes, a.lanes, a.mmax, a.kmax, a.wwords, a.rlat, a.seed, a.dir)
    raise SystemExit(0 if ok else 1)


if __name__ == "__main__":
    main()
