"""Generate the embedded weight image + expected-token self-check data for
sw/applications/kevgpt_chat/ (the Genesys2 port's Phase 5 firmware).

There is no host/DDR path on this board (unlike the KV260's A53/Linux daemon),
so the trained weight image has to be baked into the firmware image itself and
streamed into xheep_kevgpt_peripheral's W_DATA register at boot, exactly the
way fabric/stage3/tb/tb_seq_vec_kv.sv streams wrom.mem into wl_we/wl_data in
simulation (see that testbench's main initial block): one wl_rst pulse, then
every wide word split into WBITS/32 32-bit chunks, LOW chunk first
(`wword[s*32 +: 32]` for s=0..SUBW-1).

This script reuses the exact same code path fabric.stage3.run_vec_kv gates
against (seq_ref.build + write_mems_wideword + IntKVQSequencer.generate_greedy
at kbits=8/vbits=8/rotate=False/divfree=True) so the embedded expected-token
array is the identical golden reference the RTL gate is bit-exact-verified
against -- not a separately-computed value that could silently drift from it.

    python -m fabric.genesys2.gen_chat_fw \\
        --npz fabric/export_optionA/goformer.npz --meta data/char_optionA/meta.json \\
        --prompt once --ngen 6 --lanes 128 --p 8 \\
        --out ~/RVchatbot/kevgpt-genesys2-soc/sw/applications/kevgpt_chat/kevgpt_weights.h
"""
from __future__ import annotations

import argparse
import json
import os
import tempfile

from fabric.stage3 import seq_ref
from fabric.stage3.run_sequencer import write_mems_wideword
from model.goformer_kvq import IntKVQSequencer


def _encode(meta_path, text):
    m = json.load(open(meta_path))
    return [m["stoi"].get(c, 0) for c in text]


def wrom_to_words(wrom_path: str, lanes: int) -> list[int]:
    """Each wrom.mem line is `lanes` hex chars (lanes*4-bit wide word). Split
    into 32-bit chunks, low chunk first -- matches tb_seq_vec_kv.sv's
    `wword[s*32 +: 32]` streaming order exactly."""
    subw = (lanes * 4) // 32
    words = []
    with open(wrom_path) as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            wide = int(line, 16)
            for s in range(subw):
                words.append((wide >> (32 * s)) & 0xFFFFFFFF)
    return words


def emit_header(out_path, weight_words, prompt_ids, expected_gen, plen, ngen):
    npass = plen + ngen - 1
    with open(out_path, "w") as f:
        f.write("/* Auto-generated by fabric/genesys2/gen_chat_fw.py -- do not hand-edit.\n")
        f.write(" * Regenerate after retraining/re-exporting the Option A checkpoint. */\n")
        f.write("#ifndef KEVGPT_WEIGHTS_H\n#define KEVGPT_WEIGHTS_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define KEVGPT_PLEN {plen}\n")
        f.write(f"#define KEVGPT_NGEN {ngen}\n")
        f.write(f"#define KEVGPT_NPASS {npass}\n\n")

        f.write(f"static const uint32_t kevgpt_weight_words[{len(weight_words)}] = {{\n")
        for i in range(0, len(weight_words), 8):
            chunk = weight_words[i:i + 8]
            f.write("    " + ", ".join(f"0x{w:08x}u" for w in chunk) + ",\n")
        f.write("};\n")
        f.write(f"#define KEVGPT_WEIGHT_WORDS_COUNT {len(weight_words)}u\n\n")

        f.write(f"static const uint16_t kevgpt_prompt_ids[KEVGPT_PLEN] = {{"
                + ", ".join(str(int(t)) for t in prompt_ids) + "};\n")
        f.write(f"static const uint16_t kevgpt_expected_gen[KEVGPT_NGEN] = {{"
                + ", ".join(str(int(t)) for t in expected_gen) + "};\n\n")
        f.write("#endif\n")


def main(argv=None):
    ap = argparse.ArgumentParser(prog="fabric.genesys2.gen_chat_fw")
    ap.add_argument("--npz", default="fabric/export_optionA/goformer.npz")
    ap.add_argument("--meta", default="data/char_optionA/meta.json")
    ap.add_argument("--prompt", default="once")
    ap.add_argument("--ngen", type=int, default=6)
    ap.add_argument("--lanes", type=int, default=128)
    ap.add_argument("--p", type=int, default=8)
    ap.add_argument("--out", required=True)
    a = ap.parse_args(argv)

    prompt_ids = _encode(a.meta, a.prompt)
    plen = len(prompt_ids)

    p, cfg = seq_ref.build(a.npz)
    gold_seq = IntKVQSequencer(p, cfg, kbits=8, vbits=8, rotate=False, divfree=True)
    expected_gen = gold_seq.generate_greedy(list(prompt_ids), a.ngen)[plen:]

    nlayer = len(p["blocks"])
    iseq = seq_ref.IntSequencer(p, cfg)
    with tempfile.TemporaryDirectory() as td:
        write_mems_wideword(td, iseq, a.lanes, nlayer, a.p)
        weight_words = wrom_to_words(os.path.join(td, "wrom.mem"), a.lanes)

    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    emit_header(a.out, weight_words, prompt_ids, expected_gen, plen, a.ngen)
    print(f"wrote {a.out}: {len(weight_words)} weight words "
          f"({len(weight_words) * 4} bytes), prompt={a.prompt!r} "
          f"plen={plen} ngen={a.ngen} expected_gen={expected_gen}")


if __name__ == "__main__":
    main()
