"""Generate the embedded weight image + expected-token self-check data for
sw/applications/kevgpt_chat/ (the Genesys2 port's Phase 5 firmware).

There is no host/DDR path on this board (unlike the KV260's A53/Linux daemon),
so the trained weight image has to be baked into the firmware image itself and
streamed into xheep_kevgpt_peripheral's W_DATA register at boot, exactly the
way fabric/stage3/tb/tb_seq_vec_kv.sv streams wrom.mem into wl_we/wl_data in
simulation (see that testbench's main initial block): one wl_rst pulse, then
every wide word split into WBITS/32 32-bit chunks, LOW chunk first
(`wword[s*32 +: 32]` for s=0..SUBW-1).

This script reuses the exact same code path fabric.stage3.run_vec_kv gates
against (seq_ref.build + write_mems_wideword + IntKVQSequencer.generate_greedy
at kbits=8/vbits=8/rotate=False/divfree=True) so the embedded expected-token
array is the identical golden reference the RTL gate is bit-exact-verified
against -- not a separately-computed value that could silently drift from it.

    python -m fabric.genesys2.gen_chat_fw \\
        --npz fabric/export_optionA/goformer.npz --meta data/char_optionA/meta.json \\
        --prompt once --ngen 6 --lanes 128 --p 8 \\
        --out ~/RVchatbot/kevgpt-genesys2-soc/sw/applications/kevgpt_chat/kevgpt_weights.h
"""
from __future__ import annotations

import argparse
import json
import os
import tempfile

from fabric.stage3 import seq_ref
from fabric.stage3.run_sequencer import write_mems_wideword
from model.goformer_kvq import IntKVQSequencer


def _encode(meta_path, text):
    m = json.load(open(meta_path))
    return [m["stoi"].get(c, 0) for c in text]


def wrom_to_words(wrom_path: str, lanes: int) -> list[int]:
    """Each wrom.mem line is `lanes` hex chars (lanes*4-bit wide word). Split
    into 32-bit chunks, low chunk first -- matches tb_seq_vec_kv.sv's
    `wword[s*32 +: 32]` streaming order exactly."""
    subw = (lanes * 4) // 32
    words = []
    with open(wrom_path) as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            wide = int(line, 16)
            for s in range(subw):
                words.append((wide >> (32 * s)) & 0xFFFFFFFF)
    return words


def emit_tokenizer_header(out_path, meta_path):
    """Emit the C-side stoi/itos/stop-id tables `kevgpt_interactive` needs to
    encode typed input and decode generated tokens -- there is no such table
    anywhere in sw/ today (every prior firmware app only ever baked in ONE
    fixed prompt's pre-encoded ids, never a general encoder). Sourced from
    the same meta.json _encode() already reads, so this can't drift from
    what every other gate/tool in this project treats as the vocab.

    kevgpt_stoi[] is ASCII-code-indexed (0..127), -1 for anything meta.json's
    stoi has no entry for -- unlike Python's `stoi.get(c, 0)` (which maps
    unknown chars to id 0, a real character), the firmware caller decides
    the fallback explicitly at the call site, since -1 out of a lookup table
    is a clearer "not found" signal in C than overloading a valid id.

    kevgpt_stop_ids[] is computed via itos (decode), matching
    fabric/stage3/board/pl_kv256.py's own `_stop_ids` exactly and for the
    same reason: encoding the literal strings "."/"!"/"\\n" would risk
    nothing here (this vocab has no encode-side surprises), but computing
    it the same way as the already-proven KV260 reference keeps the two
    implementations directly comparable rather than coincidentally similar.
    """
    m = json.load(open(meta_path))
    stoi = m["stoi"]
    itos = {int(k): v for k, v in m["itos"].items()}
    vocab = len(itos)

    ascii_to_id = [-1] * 128
    for ch, idx in stoi.items():
        if len(ch) == 1 and ord(ch) < 128:
            ascii_to_id[ord(ch)] = idx

    stop_ids = [i for i in range(vocab) if itos.get(i) in (".", "!", "?", "\n")]

    def _c_char_literal(ch):
        # itos values are single characters, some outside ASCII (this vocab
        # has a handful of non-ASCII "junk" chars from the raw corpus) --
        # a plain 8-bit C char can't hold a full Unicode codepoint, so those
        # substitute '?' (this vocab has no real '?' token, confirmed from
        # meta.json, so the placeholder can never be confused with a real
        # generated character). Everything else emits as a numeric escape
        # so the header is valid C regardless of source encoding.
        return "\\x%02x" % (ord(ch) & 0xFF) if ord(ch) < 128 else "?"

    with open(out_path, "w") as f:
        f.write("/* Auto-generated by fabric/genesys2/gen_chat_fw.py -- do not hand-edit.\n")
        f.write(" * Regenerate after retraining/re-exporting the checkpoint. */\n")
        f.write("#ifndef KEVGPT_TOKENIZER_H\n#define KEVGPT_TOKENIZER_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define KEVGPT_VOCAB_SIZE {vocab}u\n\n")

        f.write(f"static const char kevgpt_itos[KEVGPT_VOCAB_SIZE] = {{\n    ")
        f.write(", ".join(f"'{_c_char_literal(itos[i])}'" for i in range(vocab)))
        f.write("\n};\n\n")

        f.write("/* ASCII code -> token id, -1 if this vocab has no such char. */\n")
        f.write("static const int8_t kevgpt_stoi[128] = {\n    ")
        f.write(", ".join(str(v) for v in ascii_to_id))
        f.write("\n};\n\n")

        f.write("/* token ids whose character is a sentence-ending '.', '!', '?', or '\\n'\n")
        f.write(" * (this vocab has no '?' -- included in the scan for parity with\n")
        f.write(" * fabric/stage3/board/pl_kv256.py's _stop_ids anyway). */\n")
        f.write(f"#define KEVGPT_STOP_COUNT {len(stop_ids)}u\n")
        f.write(f"static const uint8_t kevgpt_stop_ids[KEVGPT_STOP_COUNT] = {{"
                + ", ".join(str(i) for i in stop_ids) + "};\n\n")
        f.write("#endif\n")


def emit_header(out_path, weight_words, prompt_ids, expected_gen, plen, ngen):
    npass = plen + ngen - 1
    with open(out_path, "w") as f:
        f.write("/* Auto-generated by fabric/genesys2/gen_chat_fw.py -- do not hand-edit.\n")
        f.write(" * Regenerate after retraining/re-exporting the Option A checkpoint. */\n")
        f.write("#ifndef KEVGPT_WEIGHTS_H\n#define KEVGPT_WEIGHTS_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define KEVGPT_PLEN {plen}\n")
        f.write(f"#define KEVGPT_NGEN {ngen}\n")
        f.write(f"#define KEVGPT_NPASS {npass}\n\n")

        f.write(f"static const uint32_t kevgpt_weight_words[{len(weight_words)}] = {{\n")
        for i in range(0, len(weight_words), 8):
            chunk = weight_words[i:i + 8]
            f.write("    " + ", ".join(f"0x{w:08x}u" for w in chunk) + ",\n")
        f.write("};\n")
        f.write(f"#define KEVGPT_WEIGHT_WORDS_COUNT {len(weight_words)}u\n\n")

        f.write(f"static const uint16_t kevgpt_prompt_ids[KEVGPT_PLEN] = {{"
                + ", ".join(str(int(t)) for t in prompt_ids) + "};\n")
        f.write(f"static const uint16_t kevgpt_expected_gen[KEVGPT_NGEN] = {{"
                + ", ".join(str(int(t)) for t in expected_gen) + "};\n\n")
        f.write("#endif\n")


def main(argv=None):
    ap = argparse.ArgumentParser(prog="fabric.genesys2.gen_chat_fw")
    ap.add_argument("--npz", default="fabric/export_optionA/goformer.npz")
    ap.add_argument("--meta", default="data/char_optionA/meta.json")
    ap.add_argument("--prompt", default="once")
    ap.add_argument("--ngen", type=int, default=6)
    ap.add_argument("--lanes", type=int, default=128)
    ap.add_argument("--p", type=int, default=8)
    ap.add_argument("--out", required=True)
    ap.add_argument("--tokenizer-out", default=None,
                     help="also emit the stoi/itos/stop-id header kevgpt_interactive needs "
                          "(e.g. .../kevgpt_interactive/kevgpt_tokenizer.h)")
    a = ap.parse_args(argv)

    prompt_ids = _encode(a.meta, a.prompt)
    plen = len(prompt_ids)

    p, cfg = seq_ref.build(a.npz)
    gold_seq = IntKVQSequencer(p, cfg, kbits=8, vbits=8, rotate=False, divfree=True)
    expected_gen = gold_seq.generate_greedy(list(prompt_ids), a.ngen)[plen:]

    nlayer = len(p["blocks"])
    iseq = seq_ref.IntSequencer(p, cfg)
    with tempfile.TemporaryDirectory() as td:
        write_mems_wideword(td, iseq, a.lanes, nlayer, a.p)
        weight_words = wrom_to_words(os.path.join(td, "wrom.mem"), a.lanes)

    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    emit_header(a.out, weight_words, prompt_ids, expected_gen, plen, a.ngen)
    print(f"wrote {a.out}: {len(weight_words)} weight words "
          f"({len(weight_words) * 4} bytes), prompt={a.prompt!r} "
          f"plen={plen} ngen={a.ngen} expected_gen={expected_gen}")

    if a.tokenizer_out:
        os.makedirs(os.path.dirname(a.tokenizer_out), exist_ok=True)
        emit_tokenizer_header(a.tokenizer_out, a.meta)
        print(f"wrote {a.tokenizer_out}")


if __name__ == "__main__":
    main()
